[supabase]
url = "https://uyqoeoddfeiapyeiyzml.supabase.co"
access_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5cW9lb2RkZmVpYXB5ZWl5em1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1ODkwNDIsImV4cCI6MjA1NDE2NTA0Mn0.5mH7_T4jkerWwN9WJgAS2OdtCyj_owP_wCaE_qdWEis"

[openrouteservice]
api_key = "5b3ce3597851110001cf62487bac1f2922114581844c7618ff22f545"
